### ISSUE TITLE
GUI and more for the basic statistics exporter

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#101]
The new feature to export basic statistics could be used for various data sets, and exports could be both csv and html table (directly shown in browser).

There may also be a GUI where the user can select:
A. Statistics will be calculated for:
A1. Table
A2. Column

B. Statistics will only be calculated for the subset:
B1. Choosen obs_points, or
B2. Column == ('item1','item2','item3') or
B3. Column == ('item1','item2','item3') or AND AnotherColumn LIKE ('Fe%', Mn%') or
B4. obsid in select distinct obsid from (USER_SELECTED_TABLE), or...
B5. ...

See feature custom plot for GUI ideas considering A and B.

**Comment by HenrikSpa** [comment]
The plugin GroupStats can and should be used for this. If there is a need that it doesn't satisfy, we can probably implement it in that one instead of in MidvattenPlugin. Reopen this issue if there is a need that really can't or shouldn't be done in GroupStats.
