### ISSUE TITLE
Add support for importing water quality from interlab 4.0 files 

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#105]
For increased compatibility, add support for importing interlab 4.0 files:
(http://www.svensktvatten.se/Documents/Kategorier/Dricksvatten/2010-12-21_Interlab%204%200_komplett_inkl_bilagor.pdf)

The water quality data in these files are structured in two parts:
"sample admin" (staff, project, location, date_time etc) and 
"sample data" (parameter, value, unit). 

Hence it is a well prepared for a future database design where water quality data from laboratory analysis is split into two tables:
- sample metadata and
- sample water quality data

**Comment by HenrikSpa** [comment]
There might be a good idea to display the parsed data to the user and ask for confirmation of the values.

This confirmation request could also be a choice by the user (yes to always request or now to silentry try to import everything and only popup info if something is wrong like obsid not existing).

**Comment by HenrikSpa** [comment]
This format is implemented but not tested in the field yet. 

The attribute "depth" doesn't exist in interlab4, but might perhaps be put in the metadata field "Specifik provplats".

**Comment by HenrikSpa** [comment]
This is now tested in the field and the format works.
Depending on how the lab uses the file, some manual adjustments might have to be done. (missing fields etc.)
