### ISSUE TITLE
log messages and log files

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#154]
Instead of writing long log messages to msg-bar, other ways of logging could be used.

One is QgsMessageLog (messages are printed in different categories in the chat bubble in the bottom right corner.)
from qgis.core import QgsMessageLog
QgsMessageLog.logMessage('Testing', level=QgsMessageLog.INFO)

The log message can also be written to a logfile:
def writelogmessage(message, tag, level):
    #write the log message to file

QgsMessageLog.instance().messageReceived.connect( writelogmessage )

**Comment by jkall** [comment]
partial fix implemented in https://github.com/jkall/qgis-midvatten-plugin/commit/3e655249b765e8ca61b922f8a1a7d462842b7d51

But **please notice** that temporary files are yet not removed when qgis is closed. Needs to do cleanup.

The logfile is also not yet used very much in the code.

**Comment by jkall** [comment]
fixed in https://github.com/jkall/qgis-midvatten-plugin/commit/ed860f2959ec0eaa60adfe89b8123e403ee2711c
