### ISSUE TITLE
Bug when changing locale in a very specific order

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#163]
Happens if done like this:
1. Open Qgis and Midvatten settings (clean project) and changing locale.
2. Then opening a saved project.
   After that, you can't change locale (it's empty).

**Comment by jkall** [comment]
Make "locale" a setting in the database instead. When user creates a new database, there will be three blocking popups:

1. Set locale for this database
2. Set CRS (EPSG-ID) for this database
3. Give filename and path for the new database

The first step will tell the plugin to:
    * write "locale" as a variable to about_db (perhaps we need to introduce a new column "general_variable" to mark such records in the about_db table?)
    * fill some zz-tables with relevant data

Code changes that are needed: 
midvatten_utils.getcurrentlocale()
    - try: load locale from the variable "locale" in database table "about_db"
    - except (if the database is old or otherwise corrupt or this functions somehow is called without any midvatten-db is set): locale.getdefaultlocale()[1]
Any  usage of locale.get_defaultlocale()[1] or QgsProject.instance().readEntry("Midvatten", "locale")[0] shall be replaced by midvatten_utils.getcurrentlocale()

_lower priority/future fix:
it may be better ux to have one Qt Widget to let the user perform all three steps and then click "create db". The "CRS" should be proposed after setting locale. The "create db" button will also have to be inactivated until all three input data is set._

**Comment by HenrikSpa** [comment]
As it is now we only support swedish and english as locales in the code. This choice then decides:
* if insert_datadomain.sql och insert_datadomain_sv.sql should be used to fill the database with predefined values.
* which hard coded strings to use in reports.
* the attribute table column names for layers loaded with the key F7.

As it is now, only the choice sv_SE has any effect. Any other locale will fall back to en_US and use english.

So: Josefs suggestions should work just fine.

**Comment by HenrikSpa** [comment]
Solved:
- User is asked for locale when database is created.
- The locale is written to about_db: about_db now has a row where description is locale:xx_XX where xx_XX is for example sv_SE.
- utils.getcurrentlocale now returns a list like [locale_name, encoding] where locale_name is either the user set locale read from database or the default locale locale.getdefaultlocale()[0]. The encoding is always locale.getdefaultlocale()[1].
- Midvatten settings dialog still has locale as general tab. Changing this locale inserts or updates the locale setting in the database.
- Filling of zz_tables works just like before after the user has chosen the locale.
