### ISSUE TITLE
general csv importer

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#180]
One common import function for any csv file into any of the database tables. Workflow:

  1. Menu: Import csv file to database table -> QFileSelector: Select csv file
(code: parsing csv file, get number of columns and the first row as header/column descriptor)
  2. Qt Dialog. Dropdown selector where all of the database tables (Midvatten db tables, not internal db tables) are listed. User selects the target table.
  3. Qt Dialog is populated with one row for each column in the target table:
      * A. If obsid is in the target table  then
            * If obs_points layer selected and only one obs_point is selected then user may set "get obsid from map selection" 
            * Else there is a dropdown list presenting each column in the csv file which the user **must** set.
      * B. For each of the remaining columns in target table, there will be one row in the Qt dialog:
            * target table column name
            * target table column data type (and hint e.g. _text 'yyyy-mm'dd hh:mm:ss')
            * dropdown selector for corresponding csv file column (col no + text in first row)

![20161202143459088_0001](https://cloud.githubusercontent.com/assets/6205804/20837664/560f87e0-b8a5-11e6-8670-848f62d4ea00.jpg)

related issues, sanity checks etc under the hood:
https://github.com/jkall/qgis-midvatten-plugin/issues/87
https://github.com/jkall/qgis-midvatten-plugin/issues/85
https://github.com/jkall/qgis-midvatten-plugin/issues/50

**Comment by HenrikSpa** [comment]
This one is now at version 1.0 beta in branch Henrik. Everything seems to work but there is probably something that can break it.

**Comment by HenrikSpa** [comment]
Done.
