### ISSUE TITLE
avoid edits to the database when creating section plot

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#182]
For stability issues, unnecessary edits to the database should be avoided. 

Currently, a temporary table is created in the database when creating a section plot. See module _sectionplot_ class variable _self.temptableName = 'temporary_section_line'_

This is needed for the splite method _ST_Line_Locate_Point_ in method _get_length_along_

The behaviour above might be a reason for a number of problems with multi-user plotting from the same database since users are not aware that the section plot also leads to an edit - and simultaneous edits are not allowed.

Perhaps it is possible to replace this with an in-memory temporary attached splite db instead?

This is probably not an issue if changing to postGIS as db engine.

**Comment by HenrikSpa** [comment]
I think this can be done by creating a db and setting db path to ':memory:'

self.conn = sqlite.connect(':memory:')

It could perhaps be attatched to.

Another possibility is to create a temporary .sqlite-file in the temporary folder just for this.

**Comment by HenrikSpa** [comment]
I've probably solved this in branch sectionplot_nocrash using the :memory: way. I used :memory: over views way to be sure that the database itself is never changed by drawing section plots.

Whats left is to write a unit test to make sure that this doesn't change calculation of lenghtalong  and also tests where several users makes plots at the same time.

**Comment by HenrikSpa** [comment]
The uni test is done and it works well.
