### ISSUE TITLE
moving average in custom plot

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#190]
It would be very useful to have an option to calculate and plot moving average, on the fly, in the custom plot. 

I should be on the tab level, not for the full plot (i.e. as the gain, offset and remove mean but not as the max tstep).

UI implementation: 
A new line editor with number of days (decimal number accepted) for calculating moving average. Whenever moving average is set to zero (days) then this feature is inactivated.

**Comment by HenrikSpa** [comment]
This would be very easy to do using pandas. By not using pandas would have to parse a date list/array over and over again probably (for each step check which dates are within step +- half moving average step length and make average over the corresponding values).

**Comment by HenrikSpa** [comment]
Done in 46f04b8bae6c952e5bcb21ad664052eb74d568d3.
