### ISSUE TITLE
include db documentation in create statements

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#213]
Add documentation about tables and columns by adding comments to the CREATE statements. 
Then the table "about_db" may be filled automatically by extracting comments from the create statements.  

Workflow:
 1. remove most of the "insert into about_db..." in create_db.sql
 2. rewrite the create statements  in create_db.sql, with comments:
     /\*this is the table comment\*/ 
     --this is a column comment
 3. Automate inserts into the about_db, based on the create comments
python-sqlite-pseudo-code
```
    for each table:
        get comment for this table and insert into about_db
        for each column in table:
            get comment for this column and insert into about_db
```
See attached file for example of embedded comments and how to extract them.
[sqlite_samples_for_comments_and_parsing_comments.txt](https://github.com/jkall/qgis-midvatten-plugin/files/764224/sqlite_samples_for_comments_and_parsing_comments.txt)

**Comment by HenrikSpa** [comment]
This is now implemented in 1.4.
