### ISSUE TITLE
replace pyspatialite with pysqlite

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#247]
Pyspatialite does not support SpatiaLite 4.x. Pysqlite module is much more widely used and now it is possible to load spatial extensions via SQLite's load_extension() mechanism without issues.
(Info from  https://github.com/qgis/QGIS/pull/2701)

Also see:
https://groups.google.com/d/msg/spatialite-users/o0jUwMUqx_g/OEat2JTUAAAJ
and older:
https://groups.google.com/forum/#!topic/spatialite-users/iTOGhiBi83E

**Comment by HenrikSpa** [comment]
Tried it in the postgis branch, but I must install mod_spatialite.dll somehow. The group discussion also mention this.
"""
self.conn.execute("SELECT load_extension('mod_spatialite')")
OperationalError: mod_spatialite.so: kan inte \xf6ppna delad objektfil: Filen eller katalogen finns inte
"""

**Comment by HenrikSpa** [comment]
Fixed.
