### ISSUE TITLE
postgis branch and database transactions on spatialite database

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#251]
this issue affects the branch **postgis_henrik**:

When using the feature "Midvatten - Utilites - Prepare ... for ...Qgis2threejs plugin..." I get some python errors indicating the database transactions are not completetely finished when the database conncetion is closed.

Python error:  'can not commit on closed db'

**Comment by HenrikSpa** [comment]
Fixed in version 1.5.5b branch postgis_henrik
