### ISSUE TITLE
incorrect colors for strat_layers when preparing data for qgiis2threejs plugin

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#252]
This bug affects branches **postgis_henrik**  and **master**

The feature to prepare layers for Qgis2threejs plugin to create a 3D borehole visualisation do not folow the predefined color codes.

Previous behaviour was to set the loaded qgis layers (spatialite views) with colors according to stratigraphy code (to automate the process of getting correct colors in 3D visualisation). As described here:https://github.com/jkall/qgis-midvatten-plugin/wiki/7.-Utilities#prepare-layers-for-qgis2threejs-plugin-to-create-a-3d-borehole-visualisation

Now it seems the spatialite view layers ("strat_...")  symbols  have random colors. I suspect this  connection between qgis strat_-layers and symbology color may have been lost when implementing dictionaries and symbology data domains in the data base.

**Comment by HenrikSpa** [comment]
Fixed in version 1.5.5b in branch postgis_henrik
