### ISSUE TITLE
stratigraphy plot fails when h_gs is missing

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#253]
If h_gs is null but h_toc exists, create stratigraphy plot with respect to h_toc but give warning to user:
Messagebar = one message per obs_point (keep current message)
PopUp = one message per stratigraphy plot window ("Warning, h_gs is missing. See messagebar.")

**Comment by HenrikSpa** [comment]
Fixed:
Stratigraphy: If h_gs is missing, h_toc is tested, if that doesn't work, stratigraphy starts at -1.
