### ISSUE TITLE
plugin not loaded due to module import errors

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#255]
version 1.5.5b postgis branch

Plugin fails to start on some machines, but not all, with python error as below. I suspect that the inconsistent module imports may work/fail on various machines due to the local python environment (python paths).

from gui.utils.py:
```
from date_utils import datestring_to_date
from midvatten_utils import returnunicode as ru
from tools import db_utils, midvatten_utils as utils
from tools.midvatten_utils import returnunicode as ru


```

Python error:

> Couldn't load plugin midvatten due to an error when calling its classFactory() method 
> 
> ImportError: cannot import name db_utils
> 
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/josef/.qgis2/python/plugins/midvatten/__init__.py", line 33, in classFactory
>     from midvatten import midvatten
>   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/josef/.qgis2/python/plugins/midvatten/midvatten.py", line 55, in 
>     import midvsettingsdialog
>   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/josef/.qgis2/python/plugins/midvatten/midvsettingsdialog.py", line 21, in 
>     import gui_utils
>   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/josef/.qgis2/python/plugins/midvatten/tools/gui_utils.py", line 28, in 
>     from tools import db_utils, midvatten_utils as utils
> ImportError: cannot import name db_utils

**Comment by HenrikSpa** [comment]
Fixed. Try now.

My dev environment adds "tools" when I use the automatic refactoring.
