### ISSUE TITLE
adding rows to customize zz_capacity zz_capacity plots

### ISSUE THREAD

**Issue by StefanoMenichetti** [jkall/qgis-midvatten-plugin#258]
Hallo at all you, I would intend to use custom "capacity" colors to map distinct geologic formation 

So I've added correctly records  (example "1b", "1d", "bna", "b7") to zz_capacity and zz_capacity plots as in stratigraphy table, but it has no result !

Instead, standard code 1, 2, 3+ etc keeps working. The field is character in any case, it tells you something ?

Thank you in advance

Stefano Menichetti

**Comment by HenrikSpa** [comment]
Hi!
Try if the new version 1.5 solves your issue.
Regards,
Henrik
