### ISSUE TITLE
Error, you have to select a relevant layer

### ISSUE THREAD

**Issue by sambawade** [jkall/qgis-midvatten-plugin#261]
Hello,

My question is probably stupid but I can't get Midvatten to produce any plot using my data or the example data given with the tutorial.

What I'm doing:
1.create new data base
2.load default db-layer
3 import obs_point.csv
4 import w quality lab .csv
5.indicate the different parameters in midvatten setting for the piper plot
every thing is going fine until here, the diffrent layer and table are filled with the data...

Then when I try to create a piper plot (or any other) I have the folowing error : "Error, you have to select a relevant layer!"

It is probably simple but I can get thought this error....

Thanks for your help

Jonas

**Comment by HenrikSpa** [comment]
Hi!

You need to select some features in a layer containing the column obsid.
Ex:
6. Select the features with water quality in obs_points layer and select the obs_points layer in QGIS.

Also: 
Try to post questions regarding the Midvatten plugin at Stackexchange:
https://gis.stackexchange.com/search?q=midvatten

Regards,
Henrik

**Comment by sambawade** [comment]
It was simple indeed.
Tankyou for your help
