### ISSUE TITLE
error 'module' object has no attribute 'general exception handler' on Qgis 2.18.18

### ISSUE THREAD

**Issue by StefanoMenichetti** [jkall/qgis-midvatten-plugin#266]
I have just updated my Qgis at 2.18.18 Las Palmas but Midvatten updating is not successfull.
A previous version of plugins seems initially to work, where can I pick the oldest version and how I can restore it ?

Thank you very much

Stefano

**Comment by HenrikSpa** [comment]
This issue seen to appear for some but not all users!

Try to uninstall the plugin first and then install it again.

You can download order versions from hehe:
https://plugins.qgis.org/plugins/midvatten/

Check tab "versions".

Uppackning the zip file to your <userfolder>\.qgis2\python\plugins folder.

**Comment by StefanoMenichetti** [comment]
Thank you very much Henrik for you quick answer. 
I've closed Qgis and then re-installed by plugin manager and now it works !
All the best :-)
