### ISSUE TITLE
installation fails QGIS 2.18.20

### ISSUE THREAD

**Issue by kmithof** [jkall/qgis-midvatten-plugin#269]
Dear Sir/Madam, I have a Problem installing the midvatten plugin. I used the installation with QGIS and also manually downloaded the plugin. I get the following message:
This plugin is broken. Error reading metadata: general
Is there something one can do? 
Thank you and best regards
Klaus

**Comment by HenrikSpa** [comment]
Hi.
You might have to restart QGIS after you install the plugin (which you probably did if you tried to manually download the plugin).

- Do you use QGIS in Linux or Windows?
- What language/location do you use in QGIS?

**Comment by HenrikSpa** [comment]
Tested and worked for me using both Linux Mint 18.2 and Windows 10:
1. Upgraded to QGIS 2.18.20.
2. Unistalled Midvatten plugin.
3. Installed Midvatten plugin 1.5.
4. Restarted QGIS.

And it worked. 
I got an error message at step 3 in Linux (not Windows) but it worked after restarting QGIS.

**Comment by HenrikSpa** [comment]
I got your error message in QGIS3 (Error reading metadata: general)
Maybe you had installed QGIS3?

**Comment by HenrikSpa** [comment]
Closing until the problem appears again.
