### ISSUE TITLE
Customplot problem when linecolors are similar

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#279]
It's sometimes hard to see which line is which in customplot due to them getting similar colors.

Line colors seem to be set using color_list = [_num[0] for _num in np.random.rand(3,1).tolist()]

Maybe use a predefined matplotlib colorramp instead of the random one.
If the same color has to be used again (due to many lines) the linestyle could be altered from '-' to '--' to double the unique styles.

**Comment by jkall** [comment]
Perhaps use the same approach as in the plotter-script (line 837...)?
User can define a list with colors for each plot (in order) otherwise a preset list will be used
`            try:
                self.plot_colors= conf.get(splot,'plot_colors').split(list_separator)
              except:
                 self.plot_colors = expand_shrink_list_to_length(['r','g','b','c','m','y','k'],number_of_unique_plots))
`
(Same approach is used for line style and markers.)
