### ISSUE TITLE
customplot crash with resample

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#280]
For some reason, resample causes customplot to crash.
Error message: 
```
/.qgis2/python/plugins/midvatten/tools/customplot.py", line 417, in createsingleplotobject
			    table = np.array(zip(df.index, df[u'values']), dtype=My_format)
			TypeError: zip argument #2 must support iteration

```
It seems the resample function results in a dataframe where the first index field contains the text string "values" (instead of a date).

Same crashes on two different linux machines. Plugin branches "master" and "qgis2". Pandas version 0.13 and 0.17.

Although working on windows machine, plugin "ver 1.5.2".

**Comment by HenrikSpa** [comment]
Fixed using if pd.__version__ > '0.18.0': instead of try-except.
