### ISSUE TITLE
enable views as a source for water levels in section plot

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#303]
The section plot currently lets the user select from tables to add water level data to the section plot.
Add a checkbox to also include views in the dropdown menu. Change sectionplot.py,  Class SectionPlotm method fill_combo_boxes:

`tabeller = [x for x in db_utils.get_tables(dbconnection=self.dbconnection, skip_views=**False**)`

and then remove 
`tabeller.append('view_w_levels_agg')`

**Comment by HenrikSpa** [comment]
Fixed in simon_merge
