### ISSUE TITLE
custom plot discontinuous plot must be default 0 

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#312]
branch simon_merge:

It seems that default time step is 1 for discontinuous plotting in custom plot. Hence many series will be discontinuous. Should be reverted to previous behaviour, time step = 0, to always start with continuous plots unless user changes this value.
 
In addition:
When plot type is "markers" (and not "plot and markers") then some data points are not plotted at all when selecting time step 1. (Expected behaviour is to  plot all markers but discontinue the line whenever time step between data points exceed 1 day).

**Comment by HenrikSpa** [comment]
Ongoing fix (soom pushed):

value 0.0:
![image](https://user-images.githubusercontent.com/17615137/54029185-da572980-41a7-11e9-85c8-44523459d01b.png)

Value 0.05 (hourly timesteps):

![image](https://user-images.githubusercontent.com/17615137/54029237-04a8e700-41a8-11e9-982c-a91f0ea4e13c.png)

**Comment by HenrikSpa** [comment]
When I start a completely blank projekt and add a sqlite database, the value is set to 0,00 (default).

It also remembers the last used value when I exit qgis (and save projekt) and loads it again.

**Comment by HenrikSpa** [comment]
Fixed in master, qgis3_henrik and simon_merge.
Please test it and close if you agree that it works.

**Comment by jkall** [comment]
@HenrikSpa OK, defaults to 0. 
But python error when using time step=1 and plot type=marker (tested to plot w_levels - level_masl, obsid and db as in screenshot):
![image](https://user-images.githubusercontent.com/6205804/54031492-2ce81400-41af-11e9-8385-f773767421f5.png)

**Comment by HenrikSpa** [comment]
Odd.

It worked for me:

>>> import numpy as np
>>> print(np.__version__)
1.16.1

I tried the same, I think, see image below:
![image](https://user-images.githubusercontent.com/17615137/54032410-d3351900-41b1-11e9-8084-e619c9c622ec.png)

**Comment by HenrikSpa** [comment]
I reinstalled numpy version 1.13.3 and I also get that error message now.

**Comment by HenrikSpa** [comment]
Found a solution for 1.13.3

See comparable image in previous post.

**Comment by HenrikSpa** [comment]
Also works with 1.16.2.

Closing the issue. It can be reopened if encountered again.
