### ISSUE TITLE
Obs_points (view_obs_points) is not always editable

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#339]
Using QGIS >3.16 the table obs_points is not always editable. The edit "pen" that turns on editing is not clickable (grey).

**Comment by HenrikSpa** [comment]
I've changed source for obs_points from view_obs_points to obs_points in latest commit for QGIS-versions above 3.16. I verified that the original bug that was the cause for the requirement for view_obs_points is no longer an issue using QGIS 3.16 in Windows and 3.22 in Ubuntu.

**Comment by lmpuser** [comment]
Hello, thank you for the advice, i'm facing this issue too.

So, to work with 3.16 version in Windows is the only way to manage at present, correct ?
best regards
Luca

**Comment by HenrikSpa** [comment]
Hi! Before the next official Midvatten version for QGIS which will have this fix, you can load the obs_points-table and apply the style manually:

1) In QGIS, click _Layer > Add Layer > Add SpatiaLite Layer_
2) Create a _New_ connection to your database and then _Connect_
3) Select table _obs_points_ in the list and click _Add_
Apply the style:
4) Right click the old obs_points layer in the layer list and choose _Styles > Copy Style > All Style Categories_
6) Select the newly added obs_points.
7) Right click the new obs_points layer in the layer list and choose _Styles > Paste Style > All Style Categories_
8) Remove the old obs_points layer from the layer list. Having more than one layer named obs_points in the layer list is not supported in the Midvatten plugin.

Regards,
Henrik

**Comment by HenrikSpa** [comment]
Fixed in 1.6.10.
