### ISSUE TITLE
FieldLogger Android App – export/import customizations

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#54]
Add:
-  export function to create a csv file which can be used as a location file for FieldLogger Android App
-  import function to load a general purpose measurement csv file from FieldLogger Android App. 

The import should allow any measurements in the file, using ”type” as the key to identfiy wether it is w_level or w_flow data. Need to pay special attention to instrumentid in w_flow and also use unique identifier (preferrably obsid) in SUBLOCATION field.

More info on FieldLogger Android App: https://play.google.com/store/apps/details?id=nl.artesia.fieldlogger

**Comment by jkall** [comment]
This is closely related to:
https://github.com/jkall/qgis-midvatten-plugin/issues/57

**Comment by HenrikSpa** [comment]
Export:
1. The midvatten user should be able to export data to a wells.csv file from the database.
1a. The midvatten user should be able to choose what wells/measurementpoints should be extracted and the measurement types that should be requested.

Example of file format from the FieldLogger android page:

FileVersion 1;2
NAME;INPUTTYPE;HINT
Value;numberDecimal|numberSigned;in m. to top of tube
Comment;text;make comment...
NAME;SUBNAME;LAT;LON;INPUTFIELD
Well1;Well1_1;53.2983;6.6653;Value|Comment
Well1;Well1_2;53.2983;6.6653;Value|Comment
Well2;Well2_1;53.2988;6.7286;Value|Comment


Import:
The FieldLogger supports sending the result by mail.
2. Import function for the recieved result file.

Example of result format from FieldLogger android page:

LOCATION;DATE;TIME;VALUE;TYPE
Well1_1;26-08-2014;07:56:14;5.53;Value
Well1_1;26-08-2014;07:56:14;Waterlevel is high;Comment
Well1_2;26-08-2014;07:57:11;The well is dry;Comment

**Comment by HenrikSpa** [comment]
The import and export function for this is now implemented and some unit tests for it is also set up.
The manual is not yet updated with instructions.

**Comment by HenrikSpa** [comment]
The manual is updated and export, import and field usage has been tested and it seems to work nicely.

**Comment by jkall** [comment]
fixed now https://github.com/jkall/qgis-midvatten-plugin/commit/6f9cca442c5bc25ffaf8eccccbbecc25284674e1
