### ISSUE TITLE
create database triggers to update coordinates from map position

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#88]
..and also the other way around

The triggers are to replace functions:
"Update coordinates from map position"
"Update map position from coordinates"

**Comment by jkall** [comment]
Fixes are found in[ linked file](https://drive.google.com/file/d/0B1vhrFUx2OZBYVh3emJ1MnhkRjg/view?usp=sharing). Needs testing.

Also important to maintain backwards compatibility. Perhaps by looking for these triggers in the database (whenever project opened, database set, layers loaded) and just create them unless they do exist.

**Comment by HenrikSpa** [comment]
This is now implemented for new databases.
If the triggers are added to an existing database, only new inserts of points or points where the geometry or coordinates are manually updated will have their geom or east, north updated automatically.

**Comment by jkall** [comment]
fixed in 8e4fbff0fef9c0e21077030eb1da0289a5d7d4b4
