### ISSUE TITLE
getting lastcalibration doesn't work for all loggers

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#89]
In wlevels_calc_calib.getlastcalibration, the sql-request uses level_masl > 0 for getting last calibration, but many loggers are below masl in for example Skutskar so they do get the last calibration value.

To make this perfect, the adjusted value should probably have to be stored as a column in the database.

**Comment by jkall** [comment]
Proposed quick-fix: change  sql-request to use level_masl > -999

**Comment by HenrikSpa** [comment]
I set it to > -990, since there are values at -998 sometimes (which are not calibrated). -990 should take care of them all.
